### PR TITLE
Merge functionality and styling on nav, footer, property detail page, user profile page

### PR DESCRIPTION
**Pull request by jieunkxx**
## :: Type of change

- [x] Bug fix
- [x] New feature
- [x] Refactoring
- [ ] Edit convention

<br />

## :: Description
1. nav bar integration
 - re-styling pages/components to place them with nav bar
 - handle search bar visibility at navigating to pages
 - apply theme color
 <br>

2. property detail page
- add property header components
- add property menu buttons
- add property image carousel 
 <br>  

3. footer
 - add button to navigate to github page
 - add button to navigate to course homepage 
<br />

## :: screenshots
Screenshot 2023-06-08 at 11 56 42 PM
<br/>

---

Screenshot 2023-06-08 at 11 56 56 PM

---
Screenshot 2023-06-09 at 12 47 27 AM

### CODE REVIEW

**Review by pukkuKim — APPROVED** [review]
Thank you so much, Jieun!

**Comment by chohyeonkim** [comment]
Thank you so much! The changes look significantly better, but I do have a few questions regarding them:
1. Are we planning to add more stuff between those later?
image

2. Correct me if I'm wrong, but in this line,
image

it seems like you added the 'searchToggle &&' condition so that the search input only appears when we're on the 'home' page. There's a minor bug if you decrease your screen size and click on the left bar; the search input disappears. However, we can fix this later. Also, considering the gap mentioned above, we could possibly position the search bar between those elements instead of toggling it on and off.

image

thank you so much for your efforts in integrating these changes

**Review by chohyeonkim — APPROVED** [review]
lgtm

**Comment by jieunkxx** [comment]
@chohyeonkim yes, we can discuss what to do with the space on the nav bar. we can relocate the search bar or add some filter options there. 
For the bug the input bar disappears when the window size shrink is what I missed to check! omg
Let's fix it in the next sprint. I will create an issue for this.

**Pull request merged**
