### PR TITLE
feat: add virtual tour on detailed page

### PR DESCRIPTION
**Pull request by jieunkxx**
## :: Type of change

- [ ] Bug fix
- [x] New feature
- [ ] Refactoring
- [ ] Edit convention

<br />

## :: Description
- add virtual tour on property detailed page
- the component displays only when valid property is received from Zillow API
- frontend UI can be improved after other features get implemented 
<br />

## :: Screenshots
image

### CODE REVIEW

**Review by pukkuKim — COMMENTED** [review]
image

I guess some of them are not in a video format :\

**Comment by jieunkxx** [comment]
@pukkuKim yup, some of them are pdf, but also various video sources

**Comment by jieunkxx** [comment]
> image
> 
> I guess some of them are not in a video format :\


@pukkuKim what is the URL host of the content on the screenshot? I will ignore the host

**Comment by pukkuKim** [comment]
@jieunkxx I've lost track of it, but it looks like the website of the company that provides the service is https://www.seevirtual360.com/ (which means, the domain could be sth like `seevirtual360.com`).

**Review by pukkuKim — APPROVED** [review]

**Pull request merged**
