### PR TITLE
Revert "ISSUE19 - 1) Input search disappears 2) Links 3) Fontcolor"

### PR DESCRIPTION
**Pull request by czhaoca**
Reverts czhaoca/TheKimsPlusTwo#25

### CODE REVIEW

**Comment by czhaoca** [comment]
change has been merged. In case there is need to revert back.

**Comment by chohyeonkim** [comment]
Sorry,  Could you explain more about this? is there a reason for reverting?

**Comment by czhaoca** [comment]
I was not sure if I merged by accident.

**Comment by czhaoca** [comment]
> Sorry, Could you explain more about this? is there a reason for revert?

I was not sure if I merged by accident.

**Comment by czhaoca** [comment]
> Sorry, Could you explain more about this? is there a reason for revert?

Please close this request if the merge under #25  was okay. Sorry for the inconvinience it caused.

**Comment by chohyeonkim** [comment]
No worries I was planning on merging it. I will close this issue !

**Pull request closed without merging**
